# -*- coding: utf-8 -*-
"""NeuraNetwork_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6K6THYbpbiWykJsVeuu5vPFG0MuZIzJ
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor

dataframe=pd.read_csv('/content/sample_data/MalnutritionData.csv')
dataset=dataframe.values
print(dataset)

x=dataset[:,0:5]
print(x.shape)
y=dataset[:,-1]
y=np.reshape(y,(-1,1))
print(y.shape)

x_train,x_test,y_train,y_test=train_test_split(x,y)

model=Sequential()
model.add(Dense(12,input_dim=5,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()

model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])

history=model.fit(x_train,y_train,epochs=150,batch_size=20)

xnew=np.array([[9.4,10.1,10.3,10.4,10.6]])
ynew=model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0],ynew[0]))

model.save('/content/predtest.h5')

from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('/content/predtest.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("predmodel.tflite","wb").write(tflite_model)

xnew=np.array([[9.4,10.1,10.3,10.4,10.6]])
ynew=model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0],ynew[0]))